stages:
  - build
  - upload
  - release

build-test-debug-stable:
  stage: build
  image: registry.gitlab.com/dfinity-lab/open/capsules/rust-minio:latest
  tags:
    - shared
  script: |
    set -eux
    cargo build --verbose --package capsule
    cargo test --verbose --package capsule

build-test-debug-nightly:
  stage: build
  image: registry.gitlab.com/dfinity-lab/open/capsules/rust-minio:nightly
  tags:
    - shared
  script: |
    set -eux
    cargo build --verbose --package capsule
    cargo test --verbose --package capsule

build-release:
  stage: build
  image: registry.gitlab.com/dfinity-lab/open/capsules/rust-minio:latest
  tags:
    - shared
  script: |
    cargo build --package capsule --package cargo-capsule --release
  artifacts:
    paths:
      - ./target/release/capsule
      - ./target/release/cargo-capsule-test

upload-release:
  before_script: []
  dependencies:
    - build-release
  needs:
    - build-release
  stage: upload
  image: curlimages/curl:latest
  tags:
    - shared
  rules:
    - if: $CI_COMMIT_TAG
  script: |
    set -eux
    export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/capsule/${CI_COMMIT_TAG}"
    curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./target/release/capsule "${PACKAGE_REGISTRY_URL}/capsule-linux-amd64"
    curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ./target/release/cargo-capsule-test "${PACKAGE_REGISTRY_URL}/cargo-capsule-test-linux-amd64"

make-release:
  before_script: []
  dependencies:
    - build-release
  needs:
    - build-release
    - upload-release
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - shared
  rules:
    - if: $CI_COMMIT_TAG
  script: |
    set -eux
    cd capsule
    export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/capsule/${CI_COMMIT_TAG}"
    release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "[{\"name\":\"capsule-linux-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/capsule-linux-amd64\"}, {\"name\":\"cargo-capsule-linux-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/cargo-capsule-test-linux-amd64\"}]"
