[package]
name = "capsules"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
anyhow = "1.0.44"
nix = "0.22.1"
itertools = "0.10.1"