[package]
name = "cargo-capsule"
version = "0.2.25"
edition = "2021"
rust-version = "1.57"

[dependencies]
anyhow = "1.0.44"
cargo = "0.58.0"
cargo-util = "0.1.1"
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.14"
nix = "0.23.1"
sha2 = "0.9.8"
shell-words = "1.0.0"
