[package]
name = "cargo-capsule"
version = "0.2.18"
edition = "2021"
rust-version = "1.57"

[dependencies]
anyhow = "1.0.44"
cargo = "0.58.0"
cargo-util = "0.1.1"
nix = "0.23.1"
itertools = "0.10.3"
sha2 = "0.9.8"
shell-words = "1.0.0"
