name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:

  test-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - name: Install minio
        run: |
          curl -L -o /usr/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x /usr/bin/minio
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install minio
        run: |
          curl -L -o /usr/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x /usr/bin/minio
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test


  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
